Table component
IlanSirisky/pokemon-app pull request #16
Opened 2024-05-28 13:20 UTC by IlanSirisky

2024-05-30 09:01 UTC, oranroz11 requested changes

2024-05-30 09:01 UTC, oranroz11 commented on src/components/Table/Table.tsx
> +  data: any[];
please don't use any - create a type

2024-05-30 09:01 UTC, oranroz11 commented on src/components/Table/Table.tsx
> +  sx?: object;
please create a type

2024-05-30 09:01 UTC, oranroz11 commented on src/components/Table/TableBody.tsx
> +  data: any[];
add type

2024-05-30 09:01 UTC, oranroz11 commented on src/components/Table/styles.ts
> +  paddingRight: "20px",
use padding attribute that includes all padding part and use cssSpacings

2024-05-30 09:01 UTC, oranroz11 commented on src/components/Table/styles.ts
> +  margin-bottom: 38px;
use cssSpacings

2024-05-30 09:01 UTC, oranroz11 commented on src/constants/table.tsx
> +    padding: "0 0 0 70px",
use cssSpacings

2024-05-30 09:01 UTC, oranroz11 commented on src/constants/table.tsx
> +    padding: "0 40px 0 0",
use cssSpacings

2024-05-30 11:25 UTC, IlanSirisky commented on src/components/Table/Table.tsx
> +  data: any[];
Yuval is aware, said to leave it like that

2024-05-30 11:25 UTC, IlanSirisky commented on src/components/Table/Table.tsx
> +  sx?: object;
Yuval is aware, said to leave it like that

2024-05-30 11:25 UTC, IlanSirisky commented on src/components/Table/TableBody.tsx
> +  data: any[];
Yuval is aware, said to leave it like that

2024-06-02 11:50 UTC, YuvalLeviMoveoHLS approved these changes

2024-06-02 11:57 UTC, merged