Fight page
IlanSirisky/pokemon-app pull request #18
Opened 2024-05-29 18:36 UTC by IlanSirisky

2024-05-30 13:02 UTC, oranroz11 requested changes

2024-05-30 13:02 UTC, oranroz11 commented on package.json
> +    "@mui/material": "^5.15.18",
remove ^

2024-05-30 13:02 UTC, oranroz11 commented on src/components/Autocomplete/Autocomplete.tsx
>    sx?: object;
add type

2024-05-30 13:02 UTC, oranroz11 commented on src/features/fight/PokemonFightCard/PokemonFightCard.tsx
> +              }
lets create a function - 
`const getColor = (healthPercentage) => {
  if (healthPercentage > 50) {
    return "success";
  } else if (healthPercentage > 20) {
    return "warning";
  } else {
    return "secondary";
  }
};`

2024-05-30 13:02 UTC, oranroz11 commented on src/features/fight/PokemonFightCard/styles.ts
> +  background: "#c4d6c0",
color semantics

2024-05-30 13:02 UTC, oranroz11 commented on src/features/fight/PokemonFightCard/styles.ts
> +      main: "#ff9800",
if that is the palette - so maybe lets make something global for the whole project

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/FightPage.tsx
> +        />
to much code in one place - lets separate the buttons types to different components/functions - fight actions and fight button

and try to reduce duplicate code

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/styles.ts
> +  padding: 40px 40px 80px 40px;
use spacing attribute

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/styles.ts
> +  gap: 80px;
use spacing

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/styles.ts
> +  padding: "90px 60px",
use spacing

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/styles.ts
> +  gap: 32px;
use spacing

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/styles.ts
> +  padding: "30px 57.5px",
use spacing

2024-05-30 13:02 UTC, oranroz11 commented on src/pages/FightPage/styles.ts
> +  boxShadow: "0px 9px 17.6px 0px #00000040",
use spacing and color palette

2024-05-30 18:30 UTC, IlanSirisky commented on src/components/Autocomplete/Autocomplete.tsx
>    sx?: object;
Didnt understand

2024-06-02 11:56 UTC, YuvalLeviMoveoHLS approved these changes

2024-06-02 12:07 UTC, merged