Modal + Pokemon Modal Card Components
IlanSirisky/pokemon-app pull request #19
Opened 2024-05-30 08:34 UTC by IlanSirisky

2024-05-30 16:25 UTC, oranroz11 requested changes

2024-05-30 16:25 UTC, oranroz11 commented on package.json
> +    "@mui/material": "^5.15.19",
remove ^

2024-05-30 16:25 UTC, oranroz11 commented on src/components/Modal/Modal.tsx
> +  sx?: object;
add type

2024-05-30 16:25 UTC, oranroz11 commented on src/components/Modal/styles.ts
> +  box-shadow: 1px 1px 25px 0px #71787f1a;
use spacing and color spacing

2024-05-30 16:25 UTC, oranroz11 commented on src/components/Modal/styles.ts
> +  z-index: 1;
why do you need z-index?

2024-05-30 16:25 UTC, oranroz11 commented on src/features/PokemonModalCard/PokemonModalCard.tsx
> +  attributes: { label: string; value: string }[];
create type for attributes

2024-05-30 16:25 UTC, oranroz11 commented on src/features/PokemonModalCard/PokemonModalCard.tsx
> +        <StyledHeaderContent>
this both component are wrapping the same thing, so why we have two different components for that?

2024-05-30 16:25 UTC, oranroz11 commented on src/features/PokemonModalCard/styles.ts
> +  gap: "2px";
use spacing

2024-05-30 17:29 UTC, IlanSirisky commented on src/components/Modal/Modal.tsx
> +  sx?: object;
Didnt understand

2024-06-02 12:00 UTC, YuvalLeviMoveoHLS approved these changes

2024-06-02 12:11 UTC, merged