Backend connection
IlanSirisky/pokemon-app pull request #21
Opened 2024-06-06 10:18 UTC by IlanSirisky

Added connection to backend with react-query.
Refactored all project to use the Pokemon interface from the backend.
Added debounce on search.

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS requested changes

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/components/CardBody/CardBody.tsx
> +        {iconFlag && bottomIcon && (
why do you need both "iconFlag" and "bottomIcon"?

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/components/Table/TableBody.tsx
> +        {isLoading && <p>Loading...</p>}
use skeleton

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/features/cardView/PokemonBasicCard/PokemonBasicCard.tsx
>  interface BasicCardProps {
PokemonBasicCardProps

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/hooks/useFetchPokemonData.ts
> +const URL = "http://localhost:3000/api/pokemons";
move to env file

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/hooks/useFetchPokemonData.ts
> +      : "/search-pokemons";
add isOwned to the axios request params

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/features/cardView/PokemonCardView/SkeletonCardView.tsx
> +      {skeletonCards.map((_, index) => (
use cssSpacings

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/features/cardView/PokemonCardView/SkeletonCardView.tsx
> +          />
use  cssSpacings

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/features/cardView/PokemonCardView/SkeletonCardView.tsx
> +            height={314}
add width and height to SkeletonCardViewProps

2024-06-13 12:37 UTC, YuvalLeviMoveoHLS commented on src/hooks/useHandleFight.ts
> +
move to env file

2024-06-13 16:37 UTC, IlanSirisky commented on src/components/CardBody/CardBody.tsx
> +        {iconFlag && bottomIcon && (
iconFlag for if pokemon is owned, bottomIcon to check if prop was actually given.

2024-06-16 07:15 UTC, YuvalLeviMoveoHLS requested changes

2024-06-16 07:15 UTC, YuvalLeviMoveoHLS commented on src/features/cardView/PokemonCardView/SkeletonCardView.tsx
> +            height={314}
width={customWidth}
height={customWidth}

2024-06-16 07:21 UTC, merged